# Application
spring.application.name=smartq
server.port=8080

# MySQL Database
spring.datasource.url=jdbc:mysql://localhost:3306/smartq_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# JWT
jwt.secret=c21hcnRxX3N1cGVyX3NlY3JldF9rZXlfMjAyNl92aWthc19kaGF5YWxfZG9fbm90X3NoYXJl
jwt.expiration=86400000

# Mail (Mailgun - add later)
#spring.mail.host=smtp.mailgun.org
#spring.mail.port=587
#spring.mail.username=YOUR_MAILGUN_USERNAME
#spring.mail.password=YOUR_MAILGUN_PASSWORD
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true
# Mailgun
mailgun.api.key=${MAILGUN_API_KEY:placeholder-key}
mailgun.domain=${MAILGUN_DOMAIN:sandbox-placeholder.mailgun.org}
mailgun.from.email=${MAILGUN_FROM:SmartQ <noreply@example.com>}
spring.profiles.active=local
